# Generated by Django 5.1.6 on 2025-04-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
